PUT {{baseUrl}}course/courses/68b58570c3ca002ed6122fbe HTTP/1.1
Content-Type: application/json
Accept: application/json
# Authorization: Bearer {{accessToken}}

{
  "subject": "64fa12c6f1c2a5f9a8a3b2e1", 
  "duration": "6 months",
  "name": "ck Web Development",
  "image": "https://example.com/images/fullstack.jpg",
  "description": "Learn MERN stack with hands-on projects"
}