PUT {{baseUrl}}user/users/67ac4879d797262419642d82 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Nadi",
    "email": "nadim@gmail.com",
    "password": "Abcd@12345"
}