POST {{baseUrl}}auth/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Nadim Sheikh",
    "email": "nadim.sheikh.07@gmail.com",
    "password": "Abcd@1234",
    "role": "super_admin",
    "dob":"17-01-1989",
    "type":"super_admin"
}