PUT {{baseUrl}}auth/update-profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Burak IT",
    "mobile": "9874561230",
    "company_branch": "685a6fe79c6b5967d228ca63",
    "gender": "685a5ad5b638178439dab641",
    "password": "Abcd@1234",
    "passport":"A123456789",
    "mother_name": "Mother",
    "father_name": "Father",
    "language": [
        "685a5ad5b638178439dab675",
        "685a5ad5b638178439dab673"
    ],
    "password": "Abcd@1234",
    "new_password": "Abcd@1234",
    "confirm_password":"Abcd@1234",
    "image":"b613af9e0ae44fdc1e1c.jpg"
}